import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { AppShell } from "@/components/app-shell";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { useBills } from "@/lib/queries";
import { BillDialog } from "@/components/bill-dialog";
import { FileText } from "lucide-react";

export const Route = createFileRoute("/bills")({
  head: () => ({
    meta: [
      { title: "Bill Register — Pratham Pathology Lab" },
      { name: "description", content: "View, search and reprint optional patient bills generated by the lab." },
      { property: "og:title", content: "Bill Register — Pratham Pathology Lab" },
      { property: "og:description", content: "View, search and reprint optional patient bills generated by the lab." },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary" },
    ],
  }),
  component: () => <AppShell><BillsPage /></AppShell>,
});

function money(v: string | number) { return `₹${Number(v).toFixed(2)}`; }

function BillsPage() {
  const [from, setFrom] = useState("");
  const [to, setTo] = useState("");
  const [q, setQ] = useState("");
  const [billNumber, setBillNumber] = useState("");
  const { data = [], isLoading } = useBills({ from, to, q, billNumber });
  const [openId, setOpenId] = useState<string | undefined>();

  return (
    <div className="p-6">
      <h1 className="mb-1 text-lg font-semibold">Bill Register</h1>
      <p className="mb-4 text-sm text-muted-foreground">
        Only patients who asked for a printed bill appear here.
      </p>

      <div className="mb-4 flex flex-wrap items-end gap-2">
        <Field label="From"><Input type="date" value={from} onChange={e => setFrom(e.target.value)} className="h-9 w-40" /></Field>
        <Field label="To"><Input type="date" value={to} onChange={e => setTo(e.target.value)} className="h-9 w-40" /></Field>
        <Field label="Patient name"><Input value={q} onChange={e => setQ(e.target.value)} placeholder="Name" className="h-9 w-48" /></Field>
        <Field label="Bill No."><Input value={billNumber} onChange={e => setBillNumber(e.target.value.replace(/\D/g, ""))} placeholder="e.g. 12" className="h-9 w-28" /></Field>
        <Button variant="ghost" size="sm" onClick={() => { setFrom(""); setTo(""); setQ(""); setBillNumber(""); }}>Clear</Button>
      </div>

      <div className="rounded-md border">
        <table className="w-full text-sm">
          <thead className="bg-secondary text-xs uppercase text-muted-foreground">
            <tr>
              <th className="px-3 py-2 text-left">Bill No.</th>
              <th className="px-3 py-2 text-left">Bill Date</th>
              <th className="px-3 py-2 text-left">Patient</th>
              <th className="px-3 py-2 text-left">Reg No.</th>
              <th className="px-3 py-2 text-right">Net</th>
              <th className="px-3 py-2 text-right">Paid</th>
              <th className="px-3 py-2 text-right">Balance</th>
              <th className="px-3 py-2 text-right">Prints</th>
              <th className="px-3 py-2 text-right">Action</th>
            </tr>
          </thead>
          <tbody>
            {isLoading && <tr><td colSpan={9} className="p-6 text-center text-muted-foreground">Loading…</td></tr>}
            {!isLoading && data.length === 0 && (
              <tr><td colSpan={9} className="p-6 text-center text-muted-foreground">No bills generated yet.</td></tr>
            )}
            {data.map(b => (
              <tr key={b.id} className="border-b hover:bg-secondary/40">
                <td className="px-3 py-2 font-mono font-medium">{b.billNumber}</td>
                <td className="px-3 py-2">{b.billDate.slice(0, 10)}</td>
                <td className="px-3 py-2 font-medium">{b.patientNameSnapshot}</td>
                <td className="px-3 py-2 font-mono">{b.patientRegisterNumberSnapshot}</td>
                <td className="px-3 py-2 text-right tabular-nums">{money(b.netAmount)}</td>
                <td className="px-3 py-2 text-right tabular-nums">{money(b.paidAmount)}</td>
                <td className="px-3 py-2 text-right tabular-nums">{money(b.balanceAmount)}</td>
                <td className="px-3 py-2 text-right tabular-nums">{b.printCount}</td>
                <td className="px-3 py-2 text-right">
                  <Button size="sm" variant="outline" className="gap-1.5" onClick={() => setOpenId(b.id)}>
                    <FileText className="h-3.5 w-3.5" /> View / Reprint
                  </Button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <BillDialog billId={openId} open={!!openId} onOpenChange={(o) => !o && setOpenId(undefined)} />
    </div>
  );
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div>
      <div className="mb-1 text-xs uppercase text-muted-foreground">{label}</div>
      {children}
    </div>
  );
}
